### ISSUE TITLE
Pass through mouse events in gallery mode

### ISSUE THREAD

**Issue by an-electric-sheep** [ccd0/4chan-x#1119]
Proposed CSS tweak:

```css
#a-gallery, .gal-viewport, .gal-image {pointer-events: none !important;}
#a-gallery * {pointer-events: auto;}
```

It basically disables pointer events for all the elements leading down to the semi-transparent overlay and then reinstates them for all the visible UI elements of the gallery.

That way one can still interact with the thread below.
