### ISSUE TITLE
Display post number in the catalog if no subject has been posted

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ccd0/4chan-x#1297]
Mainly for styling reasons. 
Got this idea from Krautchan, where it looks kinda appealing. (http://krautchan.net/catalog/int)

If this is already possible with CSS, I excuse myself!

**Comment by ccd0** [comment]
Not sure what the long-term status of Krautchan is, but this needs a picture now.

**Comment by ididntknowicoulddothatXD** [comment]
Rip. ;_;

Basically it looked like a generic subject but with the post number instead. [No.43526462] as the subject for example if there never was one.

**Comment by saxamaphone69** [comment]
```css
.catalog-post:has(.subject:empty) .postNum {
	display: block !important;
}
.catalog-post:has(.subject:empty) .postNum::before {
	content: '[';
}
.catalog-post:has(.subject:empty) .postNum::after {
	content: ']';
	margin-left: -.5ch;
}
.catalog-post:has(.subject:empty) .postNum span {
	display: none !important;
}
```

![image](https://user-images.githubusercontent.com/877480/235350330-32820efe-6a5a-4256-ba8f-af0c62a8487d.png)

Something like this? If you're on Firefox you need to flip `layout.css.has-selector.enabled` in `about:config`.
