### ISSUE TITLE
Can we remove sideArrows?

### ISSUE THREAD

**Issue by DeliciousBrown** [ccd0/4chan-x#1331]
I couldn't find any info about hiding sidearrows and stuff on the right?
[http://i.imgur.com/1CztjNy.jpg](url)

**Comment by saxamaphone69** [comment]
In the Advanced tab of the Settings, you can add the Custom CSS:
```css
.sideArrows {
  display: none;
}
```
however it looks like you want to hide checkboxes as well, which would be:
```css
.postInfo > input,
.sideArrows {
  display: none;
}
```
if they don't hide, just add `!important`.
