### ISSUE TITLE
Option to hide "4chan pass user" clover

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1761]
The little clover that 4chan Pass users have decreases the anonymity of 4chan. An option to hide these clovers is appreciated.

**Comment by saxamaphone69** [comment]
```css
.n-pu { display: none; }
```
