### ISSUE TITLE
Way to make watched threads bold when new comments

### ISSUE THREAD

**Issue by brha92** [ccd0/4chan-x#1762]
Is there any way to make watched threads bold when there are new comments in them?

**Comment by saxamaphone69** [comment]
```css
.replies-unread {
  font-weight: bold !important;
}
```

in your Custom CSS *should* do the trick.
