### ISSUE TITLE
Fappe Tyme

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1990]
Submitter: eren
Email: kneiboi@gmail.com
Hello, Thank you for this great app. I just want to ask for some minor change. Could you please add a button to make "fappe tyme" always open? I tried to download old version of the app but chrome didn't accept it. Thank you so much!

**Comment by ubone** [comment]
\>app

**Comment by saxamaphone69** [comment]
```css
.fileThumb { display: none !important; }
```
