### ISSUE TITLE
(Suggestion) Make whatever type in the name field a different font colour (like red)

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2087]
Submitter: Anon
It's very easy to leave a name in on accent because it's hard to notice.

**Comment by saxamaphone69** [comment]
```css
#qr input[name="name"] { color: red; }
```
