### ISSUE TITLE
Toggle Image Background Transparency

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2589]
When using Tomorrow Theme or similar dark themes, images with transparent backgrounds become hard or impossible to read. Please implement a toggle for transparent backgrounds either per image or globally.

**Comment by saxamaphone69** [comment]
You could just add this to your Custom CSS:
```css
.fileThumb {
  background-color: rgba(255, 255, 255, .05);
}
```
and you'd only notice it on transparent images.
