### ISSUE TITLE
Keep separate line option for header bar?

### ISSUE THREAD

**Issue by DeckardEdward** [ccd0/4chan-x#2864]
When I have my custom board list up instead of the master board list, the length of my list seems to be just short enough that the header likes to keep all the right-side details (refresh time, thread stats, function buttons) on the same line with the list usually, but just long enough that when the refresh timer hits 0 and changes to (...), the header evidently feels the need to double itself up to make enough room to fit everything I'm asking it to hold even though there's plenty of room between my list and the timer.

Can we get a feature to tell the header to just keep the timer on a separate line from the list no matter what? That way, the timer's got all the room it needs to stretch out and not give the header any reasons to squirm around of its own accord and be distracting.

**Comment by saxamaphone69** [comment]
```css
#header-bar {
  flex-direction: column;
}
#board-list {
  align-self: flex-start;
}
#shortcuts {
  align-self: flex-end;
}
```

Some variation of this might be what you're after.
