### ISSUE TITLE
please, add a new gallery mode

### ISSUE THREAD

**Issue by fabiopesaju** [ccd0/4chan-x#2902]
the current gallery mode is very good, but we could make one where the thumbs are distributed on the entire screen, such as the thumbsplus, xnview, or windows explorer ...

![s](https://user-images.githubusercontent.com/20627847/104809172-0c853980-57ca-11eb-8e1c-e6f57eeb98cf.png)

**Comment by fabiopesaju** [comment]
or "catalog view mode" inside the thread

**Comment by saxamaphone69** [comment]
```css
#a-gallery {
	background: #fafafa;
}
.gal-viewport {
	display: none;
}
.gal-thumbnails {
	flex: auto;
	flex-direction: row;
	flex-wrap: wrap;
	border: 0;
	background: none;
}
.gal-thumb {
	line-height: normal;
	flex-grow: 1;
	width: calc(100vw / 12);
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	margin: 8px;
}
.gal-thumb::after {
	content: attr(title);
	display: block;
	margin-top: 8px;
	word-break: break-all;
}
.gal-thumb:hover {
	background: rgba(0, 190, 255, .1);
}
.gal-highlight {
	background: rgba(0, 190, 255, .2);
}
```

Here, knock yourself out. Add this to your `Custom CSS` in the `Settings > Advanced` section.
