### ISSUE TITLE
Display name information in catalog

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#3154]
Add an option to display names and tripcodes in the json catalog, similar to how the subject field is shown.

Thanks for considering.

**Comment by saxamaphone69** [comment]
```css
.catalog-container:not(:hover) > * > .postInfo > .nameBlock {
  display: inline !important;
}
```

This in your Custom CSS should do the trick. Otherwise it appears on hover.
