### ISSUE TITLE
Add a home icon! [not really an issue, more of a request]

### ISSUE THREAD

**Issue by jdroo** [ccd0/4chan-x#3175]
Added it manually in the "Custom Board Navigation" setting with [external-text:"HOME","https://www.4chan.org/"]

but an icon would look nicer, something like:
https://i.imgur.com/nkF5WpT.png

here is the icon if ya wanna do this, I tried looking thru the code to see if i could add the icon myself, but I'm not sure where to look lol

https://i.imgur.com/zDCWjyC.png

**Comment by saxamaphone69** [comment]
If you really want, change it to `external-text:" ","https://www.4chan.org/"` and then add this to your Custom CSS:
```css
#header-bar a[href="https://www.4chan.org/"]::before {
  content: "\f015";
  font-family: FontAwesome;
  font-weight: 400;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  text-decoration: inherit;
  speak: none;
  display: inline-block;
  font-size: 13px;
  visibility: visible;
}
```
