### ISSUE TITLE
[Feature Request] Port colored background captcha function from K1rakishou/Kuroba-Experimental

### ISSUE THREAD

**Issue by ghost** [ccd0/4chan-x#3196]
https://github.com/K1rakishou/Kuroba-Experimental/commit/bcbb1b66726ebc03667828b8e77ce2d99b952425
Makes the background stand out against the CAPTCHA
![Screenshot_2021-09-26-22-49-27-008_com github k1rakishou chan fdroid](https://user-images.githubusercontent.com/71166028/134818380-b2a521b9-d381-471e-83d4-4985a5f53ba1.jpg)
![Screenshot_2021-09-26-22-49-21-162_com github k1rakishou chan fdroid](https://user-images.githubusercontent.com/71166028/134818315-40023a25-867f-4206-846e-9639e6bad889.jpg)

**Comment by Bwin4L** [comment]
FWIW, you can approach it by adding this bit of custom CSS in either the built-in 4chanX CSS editor or an extension like Stylus:
```CSS
#t-bg {
        filter: invert(11%) sepia(100%) saturate(6720%) hue-rotate(297deg) brightness(82%) contrast(105%);
    }
```
Result:
![image](https://user-images.githubusercontent.com/8393203/135622443-c88389e2-0493-4dad-9d82-c8a92062d054.png)
