### ISSUE TITLE
Re-enable stock header and footer?

### ISSUE THREAD

**Issue by peddy22** [ccd0/4chan-x#3261]
Is this possible with custom CSS?

**Comment by saxamaphone69** [comment]
```css
:root.sw-yotsuba #boardNavDesktop,
#navtopright,
#navbotright {
	display: block !important;
}
```

This is probably along the lines of what you want.
