### ISSUE TITLE
Add grid gallery mode

### ISSUE THREAD

**Issue by rudolphos** [ccd0/4chan-x#3321]
Gallery mode is currently scrollable on the left side.
Would be nice if there was a grid option to easily overview all images in one window.

**Comment by saxamaphone69** [comment]
#2902 Like this? Check the Custom CSS I wrote.

**Comment by rudolphos** [comment]
@saxamaphone69 Yes, that's good enough.. Ideally would be if thumbs in grid are loaded in full resolution to avoid artifacts. Like it's done in this chromium extension - https://chrome.google.com/webstore/detail/4chan-gallery-slideshow-g/mhlgpnhdgapplfjbeedinfiibdjmcdip

It can be done via 'Replace JPG: Replace jpg thumbnails with the actual image.' option, but it consumes too much bandwidth and takes some time to enable/disable every time it's needed. I just tried it with your grid gallery script and for some reason all gallery images were loaded as small thumbs.

**Comment by saxamaphone69** [comment]
I see what you mean and you're right, you'd have to enable all types of image replacement to get the full resolution of images/videos.

I'd recommend you use that extension to achieve what you want. Otherwise, if you can be bothered enabling replace each time, here's 2 CSS options. You can change some of the numbers to achieve what you want.

```css
 #a-gallery {
	background: #fafafa;
}
.gal-viewport {
	display: none;
}
.gal-thumbnails {
	flex: auto;
	border: 0;
	background: none;
	text-align: initial;
	display: grid;
	grid-template-columns: repeat(auto-fill, minmax(20vw, 1fr));
	grid-auto-rows: minmax(300px, auto);
	grid-gap: 2px;
	grid-auto-flow: dense;
}
.gal-thumb,
.gal-thumb img,
.gal-thumb video {
	all: unset;
}
.gal-thumb {
	overflow: hidden;
}
.gal-thumb img,
.gal-thumb video {
	width: 100%;
	max-width: 100%;
	height: 100%;
	min-height: 300px;
	object-fit: cover;
	display: block; 
}
```

This keeps things in little boxes, but you can't see the full thing. Again, you could change some of the numbers to see more/less.

```css
#a-gallery {
	background: #fafafa;
}
.gal-viewport {
	display: none;
}
.gal-thumbnails {
	flex: auto;
	border: 0;
	background: none;
	text-align: initial;
	display: grid;
	grid-template-columns: repeat(auto-fill, minmax(20vw, 1fr));
	grid-gap: 2px;
	grid-auto-flow: dense;
}
.gal-thumb,
.gal-thumb img,
.gal-thumb video {
	all: unset;
}
.gal-thumb {
	overflow: hidden;
	display: contents;
}
.gal-thumb img,
.gal-thumb video {
	max-width: 100%;
	height: auto;
	object-fit: contain;
}
```

Bigger boxes, and the image will shrink to fit.
