### ISSUE TITLE
Is there a way to rezise the header and move it to the left side?

### ISSUE THREAD

**Issue by kakhulu31** [ccd0/4chan-x#3362]
I can resize the font, but not the icons. Also I can't properly (so it doesn't break when you zoom) move it to the left side.

![1682584716830056](https://user-images.githubusercontent.com/51547727/234808655-40fad092-7668-42f1-b00c-b19688996401.png)

Something like this but with bigger icons and properly positioned.

**Comment by saxamaphone69** [comment]
```css
#header-bar {
justify-content: flex-start !important;
}
#board-list {
flex: initial !important;
}
#shortcuts {
float: none !important;
}
:root.shortcut-icons #shortcuts .fa::before {
font-size: 24px !important;
}
```

See if this does what you're after.
