### ISSUE TITLE
Sauce links in catalog

### ISSUE THREAD

**Issue by unknown--** [ccd0/4chan-x#359]
Title says all
I guess also adding a ;catalog tag to the sauce options would reduce the clutter.

**Comment by saxamaphone69** [comment]
This actually can be done with Custom CSS:
```css
.catalog-post > * > .fileText > :not(:first-child):not(.fileText-original) { display: inline !important; }
```
