### ISSUE TITLE
Larger previous/next buttons in gallery

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#431]
From #353:

> Also, the bars / buttons to go to next and previous images are a bit thin (might be better on larger monitors, I use a 1440x900). You could try making them expand on hover, or just having them a little wider by default.

**Comment by fgsfdss** [comment]
I fiddled around with this a while ago by the way, didn't get anything out of it unfortunately.

**Comment by saxamaphone69** [comment]
```css
.gal-prev,
.gal-next {
	flex: 0 0 30px;
	display: inline-flex;
	justify-content: center;
	align-items: center;
	transition: flex .25s;
}
.gal-prev:hover,
.gal-next:hover {
	flex: 0 0 50px;
}
.gal-prev::after,
.gal-next::after {
	position: initial;
	transform: initial;
	border-top-width: 17px;
	border-bottom-width: 17px;
}
.gal-prev::after {
	border-right-width: 18px;
}
.gal-next::after {
	border-left-width: 18px;
}
```

Adjust the values as needed.
