### ISSUE TITLE
How do I highlight wallpapers, admins, etc. with custom CSS using the filter?

### ISSUE THREAD

**Issue by Fasmea** [ccd0/4chan-x#602]
What I want to do is highlight hiro's posts, for example https://boards.4chan.org/news/thread/1

My capcode filter: /Admin$/;highlight:moot;op:yes
My CSS: moot{box-shadow: inset 5px 0 #CA4961;}

How do I fix this?

**Comment by bakugo** [comment]
The filter adds your class to post containers. You need a `.` to select classes.

```css
.postContainer.moot {
	box-shadow: inset 5px 0 #CA4961;
}
```
