### ISSUE TITLE
Pull some rice from Appchan X

### ISSUE THREAD

**Issue by spaghetti2514** [ccd0/4chan-x#74]
![screen shot 2014-05-25 at 1 55 04 pm](https://cloud.githubusercontent.com/assets/1966861/3077704/31576d98-e43e-11e3-96e5-4fd18375bac9.png)
Things like the checkbox, post hiding button being in the post, and the menu and post hiding button only appearing when the post is hovered over would all be great things to have but can't be added with just some custom CSS.
The picture above shows the top post being hovered over, and the bottom post's checkbox being checked.

**Comment by saxamaphone69** [comment]
In case people are still interested in this, styling `input[type="checkbox"]` natively is getting a little easier. With a little CSS in your Custom CSS, you can get something pretty close to the OneeChan experience (in latest Chrome, anyway).

```css
input[type="checkbox"] {
  border: 1px solid #dedede; /* or whatever colour you want */
  background-color: rgb(255, 255, 255); /* or whatever colour you want */
  transition: background .2s;
  margin: 1px; /* may need some extra margin here and there for total consistency */
  /* vertical-align: middle; */ /* can also be used where margin may not work */
  height: 12px;
  width: 12px;
  border-radius: 2px;
  cursor: pointer;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
}

input[type="checkbox"]:hover {
  background-color: rgb(239, 239, 239); /* or whatever colour you want */
}

input[type="checkbox"]:checked {
  background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAgCAYAAAAv8DnQAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAP9JREFUOMvV0CFLQ2EYxfHfrtdiURgbmCxOmFPBJgZZ0CQD0Q+goFkwabWIyWIWFgwmy7Qp7DPI3GD7ACZlYLNcy31ljG0aDHrSy3N43nOef6ZULBiifczEQ8wV7OAtGmBO4wgfOI2whsXUnMAJ8rhCJ8IxDpHDHpZwixqM5XPZBBtYxioauEgjRLjBI2bRxTneQ6EYCS4xiTu89DbONJrtP88hwnV64hm28YRqyPsFDkmSGKUYFubnsqignM7rqDWa7dcAqoLdnsXwrgZQ5QG/l8MVIxX1ZPar/lUyUOsv+aMzv+0Qw3OrM4VNrKfzB9yXioVu6LDVx+EA4/+Gwycw/Uz36O07WwAAAABJRU5ErkJggg==);
  background-repeat: no-repeat;
  background-position: 1px 1px; /* if you view the original background-image taken from OneeChan, you can estimate what number these should be if you want a light checkbox, or even choose your own background-image */
}
```

![image](https://user-images.githubusercontent.com/877480/79091568-2011f880-7d91-11ea-8855-fb93d2bb48e4.png)

As for the hiding button "in" the post, something along the lines of:

```css
.postContainer { position: relative; }
.postContainer .hide-reply-button { position: absolute; top: 0; right: 0; display: none; }
.postContainer:hover .hide-reply-button { display: block; }
```

would get the same effect.
